# Generated by Django 6.0.1 on 2026-02-21 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='action',
            field=models.CharField(blank=True, choices=[('BUY', 'Buy'), ('SELL', 'Sell')], max_length=4, null=True),
        ),
    ]
