# Generated by Django 6.0.1 on 2026-02-21 18:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_order_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='entry_price',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='stop_loss',
            field=models.DecimalField(decimal_places=4, max_digits=19, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='order',
            name='take_profit',
            field=models.DecimalField(decimal_places=4, max_digits=19, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
