# Generated by Django 6.0.1 on 2026-02-21 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_alter_order_entry_price_alter_order_stop_loss_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='broker_order_id',
        ),
    ]
