# Generated by Django 6.0.1 on 2026-02-21 07:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BrokerAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active_status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('account_id', models.CharField(max_length=100, unique=True)),
                ('api_key', models.CharField(max_length=255, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='broker_account', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Broker Account',
                'verbose_name_plural': 'Broker Accounts',
                'db_table': 'broker_account',
                'indexes': [models.Index(fields=['user', 'active_status'], name='broker_acco_user_id_502e2d_idx'), models.Index(fields=['account_id'], name='broker_acco_account_dbc7e0_idx')],
            },
        ),
    ]
