# Generated by Django 6.0.1 on 2026-02-21 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='brokeraccount',
            name='account_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
