# Generated by Django 6.0.1 on 2026-02-21 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0002_brokeraccount_account_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='brokeraccount',
            name='api_key_hash',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='brokeraccount',
            name='api_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
