# Generated by Django 6.0.1 on 2026-02-21 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0003_brokeraccount_api_key_hash_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brokeraccount',
            name='account_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
