# Generated by Django 6.0.1 on 2026-02-21 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0005_tradingsignal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tradingsignal',
            name='ip_address',
        ),
        migrations.AddField(
            model_name='tradingsignal',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tradingsignal',
            name='status',
            field=models.CharField(choices=[('success', 'Success'), ('failed', 'Failed')], default='success', max_length=20),
        ),
    ]
