# Generated by Django 6.0.1 on 2026-02-21 18:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0006_remove_tradingsignal_ip_address_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tradingsignal',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='signals_account', to='broker.brokeraccount'),
        ),
        migrations.AlterField(
            model_name='tradingsignal',
            name='raw_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tradingsignal',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='tradingsignal',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signals_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
