# Generated by Django 6.0.1 on 2026-02-21 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0007_tradingsignal_account_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradingsignal',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
